### ISSUE TITLE
Results returned at the wrong time

### ISSUE THREAD

**Issue by dipapaspyros** [LinDA-tools/QueryBuilder#2]
Follow the next step:
- Create a complex query
- Run it (it should take some time)
- While the previous query is pending, change the editor to contain a much simpler query
- Run query #2
- Results from #2 populate the results table
- Some time later (depending on its complexity), results of query #1 overwrite results from query #2

Expected behavior:
As long as i run a new query, old queries should be cancelled

**Comment by judie90** [comment]
By any chance, is this problem still valid on the latest version of the query builder? I am trying to replicate the problem, but when I run a "longer" query, I cannot change anything from the querybuilder until the results are displayed (there is the loading image being displayed)

**Comment by dipapaspyros** [comment]
Yes, fixed because of the loading image
